_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
                - 55
            "4": 3.11.2
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
